image: python:3

before_script:
  - pip install mkdocs

build:
  stage: build
  tags:
    - sztaki-docker
  script:
  - mkdocs build --strict --verbose --site-dir html
  artifacts:
    paths:
    - html
